language: generic
arch: amd64
os: linux

script:
- cd $HOME
- wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz
- tar xzf cmake-2.8.12.2.tar.gz
- cd cmake-2.8.12.2
- ./configure --prefix=$HOME/software
- make
- make install